### ISSUE TITLE
bootstrap broken

### ISSUE THREAD

**Issue by benoitc** [ngerakines/etap#2]
While trying to create make file :

./bootstrap
./configure && make

I get following error 

make[2]: **\* No rule to make target `overview.edoc', needed by`.run_edoc'.  Stop.
make[1]: **\* [all-recursive] Error 1
make: **\* [all-recursive] Error 1
enlil:etap benoitc$ ls

Also it seems that build process is different from the one in README or did I missed something ?

**Comment by ngerakines** [comment]
I've removed the framewerk dependancy.
